### ISSUE TITLE
Feature Request: Bessere Hilfe für positive Matrixeinträge

### ISSUE THREAD

**Issue by Nibbels** [Nibbels/Repetier-Firmware#2]
Wir sollten eine Art Selbsttest einbauen, der Anweisungen ausgibt, ob man die Z-Schraube weiter raus oder weiter reindrehen sollte.

**Comment by renwin** [comment]
Wie wäre eine User freundlichere Fehlerausgabe bzw. Erweiterung.
Mir hätte ein "Ihre Z-Achse ist zu niedrig. Abstand des Z-Endstops vergrößern" gereicht.
Leider kann nicht jeder programmieren und ein Z>0 ist nicht immer gleich verständlich.

**Comment by Nibbels** [comment]
Ja, völlig klar.
Anfangs wusste ich noch nicht genau, welche Auswirkungen manche Zustände in der Matrix oder anderen Variablen haben. 
Ich werde das demnächst ausgeben lassen!

LG

**Comment by Nibbels** [comment]
https://github.com/Nibbels/Repetier-Firmware/commit/52e61501a0b8a5dc4a4797283625d6d9567f2262

Dort habe ich einen Link auf ein Hilfethema im Forum eingefügt und die Beschreibung etwas erweitert. Daran kann sich demnächst noch was ändern, aber es ist ein Anfang :)

LG

**Comment by Nibbels** [comment]
Issue- und Ideenliste gibts jetzt bei https://github.com/RF1000community/Repetier-Firmware/issues
