### ISSUE TITLE
Menü für Druckbereich

### ISSUE THREAD

**Issue by renwin** [Nibbels/Repetier-Firmware#5]
Ein kleines Untermenü mit der Funktion den Druckbereich mittels 4 Positionen
zu bestimmen. Also z.B.
Pos 1:
Fahren Sie ihren Extruder mit dem Joystick oder per Hand nach vorne Links.
Pos 2:
Fahren Sie ihren Extruder mit dem Joystick oder per Hand nach hinten Links.
Pos 3:
Fahren Sie ihren Extruder mit dem Joystick oder per Hand nach vorne Rechts.
Pos:
Fahren Sie ihren Extruder mit dem Joystick oder per Hand nach hinten Rechts.
Speichern?
Ja

**Comment by Nibbels** [comment]
Was meinst du mit "den Druckbereich bestimmen"?
Der Drucker kann selbst nicht rausfinden, wie groß sein Druckbereich ist, das ist fest in die Firmware eingetragen.

LG

**Comment by renwin** [comment]
Ist es nicht möglich Scanbereich und Druckbereich "gleich zu setzen" und es somit dann im EPROM zu speichern?

**Comment by Nibbels** [comment]
Wir haben ja schon privat geschrieben: Der Drucker hat den Druckbereich fest einprogrammiert, weil klar ist, wie groß seine Platte ist. 
Er kann diese Größe nicht so einfach selbst rausfinden.
